server:
  port: 8081

spring:
  application:
    name: spring-activiti-demo-api
  datasource:
    url: jdbc:mysql://localhost:3306/spring-activiti-demo-api?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  activiti:
    database-schema-update: true
    check-process-definitions: false
    # 检测身份信息表是否存在
    db-identity-used: false
# mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #全局映射器启用缓存
    mybatis.configuration.cache-enabled: true
    #查询时,关闭关联对象及时加载以提高性能
    mybatis.configuration.lazy-loading-enabled: false
    #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    mybatis.configuration.aggressive-lazy-loading: false
    #允许返回不同的结果集以达到通用的效果
    mybatis.configuration.multiple-result-sets-enabled: true
    #对于批量更新操作缓存SQL以提高性能
    mybatis.configuration.default-executor-type: REUSE
    #数据库执行超时时间

custom:
  #datasource:
  #url: jdbc:mysql://localhost:3306/spring-activiti-demo-api?useUnicode=true&characterEncoding=utf8
  #driverClassName: com.mysql.cj.jdbc.Driver
  #username: root
  #password: 123456
  global:
    #name:
    #version:
    #copyrightYear:
    #demoEnabled:
    profile: /Users/simonxue/Developer/Temp
    #addressEnabled: